### ISSUE TITLE
[Feature Request]: Public Teams RoleVerifier and SharedClock setup

### ISSUE THREAD

**Issue by ryanbliss** [microsoft/live-share-sdk#102]
**Describe your user scenario**

If a developer wants to use our `RoleVerifier` or `SharedClock`, they must first use `joinContainer`. If a developer wants to use Live Share DDS for a custom container that doesn't use our mapping service, we currently force them to implement their own shared clock and role verifier, even if they want to use the Teams APIs.

**Describe the solution you'd like**

Either public exports for role verifier and shared clock or public API for initializing/starting those two services.

**Comment by huntj88** [comment]
does #61 solve this? To use a custom container, you end up implementing your own ILiveShareHost anyway

**Comment by Stevenic** [comment]
@ryanbliss  and I were talking about adding a `LiveShareClient.initialize()` method that would initialize the Timestamp Provider and Role Verifier without the need to call `joinContainer()`. Should be an easy add..

**Comment by huntj88** [comment]
@Stevenic Would that be something that should maybe be a static function for those that don't want an instance of `LiveShareClient` if they plan to use `AzureClient` only? 

`(new LiveShareClient(altHost)).initialize()`
vs
`LiveShareClient.initialize(altHost)`

![image](https://user-images.githubusercontent.com/10103298/196560333-04af943f-aa1f-4d23-b7a5-9bad2f9058b8.png)

**Comment by ryanbliss** [comment]
Should be fixed with #562...at least mostly. Might still be improvements we can make long term, but I think the new `AzureLiveShareHost` and `LiveShareRuntime` implementations together make this easier.
