### ISSUE TITLE
[Feature Request]: Refresh role cache every 5 minutes

### ISSUE THREAD

**Issue by ryanbliss** [microsoft/live-share-sdk#103]
Roles for `clientId` in server refresh every 5 minutes. We need to refresh the SDK cached roles every 5 minutes as well so that role changes are updated without refreshing the application.

**Comment by huntj88** [comment]
@ryanbliss @Stevenic There is already a cache refresh every minute
https://github.com/microsoft/live-share-sdk/blob/main/packages/live-share/src/internals/RoleVerifier.ts#L11

If you want to change the refresh to 5 minutes let me know

**Comment by huntj88** [comment]
I can't read, was set a once an hour, not once a minute
