### ISSUE TITLE
[Bug]: Cannot draw a dot / single point stroke by clicking without dragging cursor

### ISSUE THREAD

**Issue by ryanbliss** [microsoft/live-share-sdk#106]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [X] I have reviewed the FAQ and known issues and did not find my topic

**Describe the bug**

Cannot draw a dot / single point stroke by clicking without dragging cursor

**To Reproduce**

In any of the Live Share canvas samples, click without moving the mouse cursor. No stroke will appear in the canvas. 

**Expected behavior**

A single point will appear in the canvas at the point which the user clicked/tapped.

**Comment by corinagum** [comment]
FYI @dclaux, I did notice this also applies to the point eraser, but I mistakenly assumed it was intentional.

**Comment by dclaux** [comment]
@corinagum I can't repro that, single point erase does work.

**Comment by corinagum** [comment]
@dclaux just checked again and I can't repro either - sorry for the noise.
