### ISSUE TITLE
[Feature Request]: Add logic to limit the number of roles that can be enumerated for `LivePresence`

### ISSUE THREAD

**Issue by Stevenic** [microsoft/live-share-sdk#118]
**Describe your user scenario**

Nothing prevents an app from trying to lookup roles for every member of a 1000 person meeting which would cause us to get throttled by Graph.  

**Describe the solution you'd like**

Add logic to `LivePresence` to throttle the number of calls allowed by a client on a per/hour basis. The exact limits are TBD.

**Comment by Stevenic** [comment]
@ryanbliss do you have thoughts on throttle limits? I was thinking like 50 calls per session or something.

**Comment by ryanbliss** [comment]
@stevenic that is probably fine. Only problem is that having it hardcoded into the SDK means it is difficult to change without sdk upgrades, so it is harder to resolve live site issues that could result. Still probably better than nothing though.

Note: with the new presence proposal it is possible this will become obsolete.

**Comment by ryanbliss** [comment]
Now obsolete with #516
