### ISSUE TITLE
[Feature Request]: Switch fluid & teams-js dependencies from ~X.X.X to ^X.X.X

### ISSUE THREAD

**Issue by ryanbliss** [microsoft/live-share-sdk#121]
Fluid has confirmed that 1.0.0 brought semver support and commits to non-breaking minor / major releases. Before releasing to 1.0.0, we should upgrade our dependencies + dependency charts to ^1.X.X for Fluid and Teams JS to ^2.X.X

**Comment by corinagum** [comment]
Let me add this to my current PR.

**Comment by corinagum** [comment]
Right now we have the bumped versions of both packages - closing as resolved.
