### ISSUE TITLE
[Bug]: Dice LiveShare sample is missing a step to make it work

### ISSUE THREAD

**Issue by davrous** [microsoft/live-share-sdk#125]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [X] I have reviewed the FAQ and known issues and did not find my topic

**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**

Following the actual step by step tutorial to load the Dice LiveShare sample won't work. You need to tell to people to generate an App ID and insert it inside the manifest. Otherwise, Teams won't load the manifest because of a parse error. 

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to https://github.com/microsoft/live-share-sdk/tree/main/samples/01.dice-roller#create-the-app-package-to-sideload-into-teams
2. You need to explain how to generate an App ID and to insert it in the manifest

The same issue is there: https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-tutorial

**Expected behavior**

Provide a link to https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#id to explain how to generate an ID and provide a fake ID to let developers side load the app. 

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop(s) (please complete the following information):**

- OS: Windows 11
- Browser: Edge
- Version 106

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by Stevenic** [comment]
@davrous We can clarify this in the readme but any ID will work. Just use an online GUID generator or something to generate an ID.
