### ISSUE TITLE
[JS Bug]: Error when trying to run "npm install" in javascript/21.react-media-template

### ISSUE THREAD

**Issue by lschutze** [microsoft/live-share-sdk#194]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [x] I have reviewed the FAQ and known issues and did not find my topic

**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

When trying to run `npm install`, got a npm login error.
![image](https://user-images.githubusercontent.com/118461120/202776734-7422b850-b90a-45cf-baa3-4e3beb1d99ae.png)

After login, when trying again to run `npm install`, got:
![image](https://user-images.githubusercontent.com/118461120/202776968-07a67482-3406-4f47-accd-48a7b8172cf4.png)

**To Reproduce**

1. Go to `samples/javascript/21.react-media-template`
2. Run on `npm install`
4. See the first error described
5. Run `npm login` to login in npm
6. Run `npm install`
7. See the second error described

- OS: Windows 10
- Browser Chrome
- Version 107

**Comment by jlongo-encora** [comment]
I'm experiencing the same issue:

`
live-share-sdk/samples/javascript/21.react-media-template$ npm install
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jlongo/.npm/_logs/2022-11-18T18_18_22_074Z-debug-0.log
`

OS: Ubuntu 20.04.5 LTS
Node: v16.18.1
NPM: 8.19.2

**Comment by lschutze** [comment]
Just follow these Build Packages & Samples instructions in main page README.

**Comment by lschutze** [comment]
I think it might be a good action to adjust the samples documentation to prevent people from getting this error.

**Comment by davrous** [comment]
I had the same issue (I didn't with previous versions). I had to npm login and then delete .nvmrc and package-lock.json files. Then "npm install" worked. 

The main doc: https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-quick-start is then broken and should be fixed.

**Comment by ryanbliss** [comment]
#200 will fix this issue hopefully. Thanks for calling this out! Some references to a private npm feed got included in our sample package-lock files by accident and resetting the package-lock files exposed some other minor issues as well. Hopefully we'll get this merged soon :)
