### ISSUE TITLE
[Bug] npm install requires --legacy-peer-deps which causes problems with Teams Toolkit

### ISSUE THREAD

**Issue by corinagum** [microsoft/live-share-sdk#27]
`@fluidframework/azure-client` is a default dependency of the SDK's `live-share` package. When running `npm install`, adding `--legacy-peer-deps` is currently necessary due to differing package versions within `@fluidframework/azureclient`. 

Unfortunately, using `--legacy-peer-deps` will cause issues if you are also using Teams Toolkit. 

To fix, we will bump the fluid package that removes this requirement as soon as possible after it is released.

**Comment by ryanbliss** [comment]
Fixed with #39. Should mark as closed once we publish to NPM.

**Comment by ryanbliss** [comment]
Closed with #59
