### ISSUE TITLE
ngrok command is incorrect in documentation, project is running on 8080

### ISSUE THREAD

**Issue by sagarM-MSFT** [microsoft/live-share-sdk#333]
Hello Team,

We observed [01.dice-roller](https://github.com/microsoft/live-share-sdk/tree/main/samples/javascript/01.dice-roller#create-a-ngrok-tunnel-to-allow-teams-to-reach-your-tab-app) sample is running on port 8080 but in documentation its mentioned as port 3000.
Could you please correct the ngrok command. "ngrok http 8080 --host-header=localhost"

_**Documentation -**_ 
![image](https://user-images.githubusercontent.com/85691087/215407833-45c8b4be-5c1c-4fa7-88dd-d3200c4cd682.png)

_**Project running port -**_ 

![image](https://user-images.githubusercontent.com/85691087/215407485-eebcaee5-4ea4-46c0-818c-66cd6a8f23f7.png)

**Comment by corinagum** [comment]
This item has been fixed in a previous PR. 🙂 Port is now 3000 to match other samples.
