### ISSUE TITLE
LiveShareClient.joinContainer() throws error 500 for federated user

### ISSUE THREAD

**Issue by mscherotter** [microsoft/live-share-sdk#368]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [X] I have reviewed the FAQ and known issues and did not find my topic

**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**
On one Window/Edge user participating in a Teams meeting initializing a stage canvas, the LiveShareClient.joinCointainer() fails with throwing an exception
500, message: 'Internal error encountered while performing the required operation'
This does not happen on other clients.  Our Teams are on different tenants.

```
const containerSchema = {
    initialObjects: {
        presence: LivePresence,
    },
};

await app.initialize();

const host = LiveShareHost.create();
const client = new LiveShareClient(host);
await client.joinContainer(containerSchema);
```

- OS: Windows 11
- Browser Latest Edge

**Comment by pradeepananth** [comment]
As discussed, this was due to a known Teams issue, Calling and Meetings are rolling out a fix.
![image](https://user-images.githubusercontent.com/5934356/218856288-8e5a8fb2-65f9-4e6f-90dd-989b754e3305.png)

**Comment by ryanbliss** [comment]
Closing as we couldn't repro and this is believed to be resolved.

**Comment by adammiribyan** [comment]
This is still happening.

**Comment by pradeepananth** [comment]
@adammiribyan  - Could you please raise a new Issue with network capture for the request which threw the 500 error?
