### ISSUE TITLE
[Feature Request]: The ability to get the current strokes data, and the ability to restore the strokes data

### ISSUE THREAD

**Issue by jianwenjuan** [microsoft/live-share-sdk#383]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [x] I have reviewed the FAQ and known issues and did not find my topic

**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe your user scenario**

> When I use the live-share-canvas, I want to capture the inking and markup as a snapshot, and saved the strokes from the current inking session. When a snapshot is selected, the current inking session should be replaced with the contents of the snapshot.

**Describe the solution you'd like**

> Provide a clear and concise description of what you want to happen, with code snippets or pseudo code as applicable.

**Describe alternatives you've considered**

> Could you provide a method to get the current strokes data, and provide a method to set the strokes data?

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by ryanbliss** [comment]
Thanks @jianwenjuan! We have a work item to export the raw strokes _and_ to export the strokes as an SVG. The restoration option seems reasonable. How are you thinking about doing this in your app? Would you store the strokes in a database elsewhere, or are you talking more about undo/redo commands?

**Comment by jianwenjuan** [comment]
@ryanbliss Yes, we could store the strokes and the snapshots in a database, then we can restore the strokes data in the shared-canvas, and these strokes could still be shared with other users.
