### ISSUE TITLE
[TASK]: Add eslint/prettier to packages

### ISSUE THREAD

**Issue by Stevenic** [microsoft/live-share-sdk#55]
We should add TSLint to our packages prior to GA as additional sanity check.

**Comment by corinagum** [comment]
I'll go ahead and start this work. Since tslint is deprecated, I'll be doing a combo of eslint and prettier instead.

**Comment by Stevenic** [comment]
@corinagum is this done?

**Comment by corinagum** [comment]
@Stevenic finishing up today -- delay was due to the re-vote. Sorry for the wait.
