### ISSUE TITLE
[Feature Request]: Add ability to set tick rate for LiveTimer

### ISSUE THREAD

**Issue by ryanbliss** [microsoft/live-share-sdk#63]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [X] I have reviewed the FAQ and known issues and did not find my topic

**Describe your user scenario**

A developer can set the tick rate for the `onTick` listener in `EphemeralTimer`. This is useful for developers who may only need to update their UI or have some recurring callback once on some pre-defined interval.

**Comment by corinagum** [comment]
Resolved by #109
