### ISSUE TITLE
meeting.getAppContentStageSharingState() does not trigger callback on iOS

### ISSUE THREAD

**Issue by mscherotter** [microsoft/live-share-sdk#639]
- [X] I have reviewed the FAQ and known issues and did not find my topic

**Describe the bug**
on iOS (as identified by certification team on iPhone) and by me on iPad, calling meeting.getAppContentStageSharingState() from stage frame does not trigger the callback to be called.
In the code below, the status message "Getting meeting sharing state..." is displayed but nothing else.  The code works on all other supported devices and platforms.

`    
     export function getStageSharingStateAsync(): Promise<IAppContentStageSharingState2>{
        $(".StartingShow .StatusText").text("Getting meeting sharing state...");
    
    return new Promise((resolve:any, reject:any)=>{
        meeting.getAppContentStageSharingState((error:SdkError, result:meeting.IAppContentStageSharingState)=>{
            if (error){
                $(".StartingShow .StatusText").text(`Error getting sharing state: ${error}`);
                reject(error);
            } else{
                $(".StartingShow .StatusText").text(`Got Sharing State: ${JSON.stringify(result)}`);
                resolve({
                    isAppSharing: result.isAppSharing,
                    isShareInitiator: (result as any).isShareInitiator
                });
            }
        });
    });

}
        `

> Provide a clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:

**Expected behavior**

> Provide a clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop(s) (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [e.g. iPad]

**Additional context**

> Add any other context about the problem here.

**Comment by huntj88** [comment]
closing, being handled here
https://github.com/OfficeDev/microsoft-teams-library-js/issues/1792
