### ISSUE TITLE
[Bug]: Presence object does not have localUser object

### ISSUE THREAD

**Issue by mscherotter** [microsoft/live-share-sdk#640]
- [X] I have reviewed the FAQ and known issues and did not find my topic

I have updated my code to use the new localUser object on the LivePresence class.  Using the test live share server running on localHost, the presence object that is the first argument of the presenceChanged event does not have the localUser object.  It has the previous userId, data, and state properties.

![image](https://github.com/microsoft/live-share-sdk/assets/641702/146eb24d-ddbe-4d82-aa58-44db63417d0e)

> Provide a clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:

**Expected behavior**

> Provide a clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop(s) (please complete the following information):**

- OS: [e.g. macOS]
- Version liveShare 1.0.1

**Smartphone (please complete the following information):**

- Device: Wndows
- OS: Windows 11
- Browser Edge

**Additional context**

> Add any other context about the problem here.

**Comment by huntj88** [comment]
The `LivePresenceUser` `userPresence` variable in your screenshot still has `userId`, `data`, and `state` properties, which are the grayed out properties in your screenshot.

`LivePresence.localUser` is a property on the top level `LivePresence` object, not the `LivePresenceUser` object returned in `onPresenceChanged`. 

The `localUser` property returns a `LivePresenceUser` object which is the same type as the one returned in `onPresenceChanged`.

Does that help?

`LivePresence` also starts to listen for other presence updates before the local user is finished initializing.
If you use the top level `LivePresence.localUser`, there is a chance you could receive `onPresenceChanged` updates for other clients before the `localUser` is defined.

**Comment by mscherotter** [comment]
This is after the initialization.  The problem is that the Typescript definition of the LivePresence object no longer has the userId, data, and state properties - I have to cast to <any> have my TypeScript code compile.

**Comment by ryanbliss** [comment]
@mscherotter I'd recommend making your app robust around whether or not the localUser is defined or not. That can take a second before it is ready, since it is an asynchronous operation to fetch the user info. There should be no reason to cast as long as your app can handle localUser being undefined temporarily.
