### ISSUE TITLE
presenceChanged callback not getting called on Android Teams app.

### ISSUE THREAD

**Issue by mscherotter** [microsoft/live-share-sdk#647]
- [X] I have reviewed the FAQ and known issues and did not find my topic

**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**
My app that uses live presence works on Window desktop and browser but when running on my Android phone using the Teams app, the  presenceChanged event is not getting called at all for remote and local presence events.  On the Windows device (running on Edge) the presence changed events are getting called for remote and local events.

```
            _presence.on("presenceChanged", onPresenceChanged);

            await _presence.initialize(data);
```
When I call `_presence.update(data, PresenceState.online)` on Android, I get an error "The local user doesn't meet the app requirements to send a message for this object."

**To Reproduce**

> Steps to reproduce the behavior:

**Expected behavior**
Presence events are triggered on all Teams clients.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop(s) (please complete the following information):**

- OS:  Android
- Version 1416

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S22
- OS: latest
- Browser n/a
- Version 

**Additional context**

> Add any other context about the problem here.

**Comment by huntj88** [comment]
@mscherotter We are unable to replicate the `presenceChanged` callback not being called on android, can you tell us a little more about your scenario?

**Comment by mscherotter** [comment]
I have built a scenario based on this sample https://github.com/freistli/LiveShareCanvasBabylon
On android, this call
` await _presence.update(data, PresenceState.online);`

throws an exception "The local user doesn't meet the app requirements to send a message for this app."  Does Teams on Android need any additional permissions?  the code works just fine running in Edge or the Teams desktop app on Windows 11.

This is the container schema that I am using:
```
const containerSchema = {
    initialObjects: {
        appState: LiveState<IShowState>,
        presence: LivePresence<IAvatarData>,
        notifications: LiveEvent,
        liveCanvas: LiveCanvas
    },
};
```

Michael

**Comment by ryanbliss** [comment]
Another partner has reported this same issue. Our mobile team is investigating now.

**Comment by huntj88** [comment]
@mscherotter Are you specifying allowed roles in the initialize function for presence? I see that you are not in the sample you linked.

**Comment by ryanbliss** [comment]
We found the issue. There is an Android client issue that we were finally able to repro and pinpoint. The teams-js response Android was sending for one of our APIs is formatted incorrectly in some cases. We will work on an update to the Android client, but fortunately all of the data needed is in the response. A polyfill that we tested solved the issue, so we will fix this in the next update!

**Comment by ryanbliss** [comment]
This has been published as of version 1.0.2, or for turbo/react packages, 1.0.2-preview.1. Thanks for your patience!

**Comment by mscherotter** [comment]
I am seeing this issue and I am not using the turbo/react package.

**Comment by mscherotter** [comment]
@huntj88 I see the issue whether I pass the allowed roles or not. I have tried both scenarions.
