### ISSUE TITLE
Live Share not working

### ISSUE THREAD

**Issue by Anirbanlateetud** [microsoft/live-share-sdk#649]
After doing all the set-up and experiments, Live share is not working from different machine. After adding the App in teams, remote machine can't view the app or gets a blank screen. The app is independently working fine collaboratively from a laptop when we run multiple instances but not working from other laptop. Note: all the laptops are from same domain that are used for testing. Need help!
Thanks!

**Comment by ryanbliss** [comment]
Closing as stale, but feel free to leave more information to help reproduce. Thanks!
