### ISSUE TITLE
Unable to add Live Canvas sample to teams tabs

### ISSUE THREAD

**Issue by Kalyan492** [microsoft/live-share-sdk#650]
Hi, I am new to creating teams applications. I am trying to use the samples provided for live-share-sdk ("samples\javascript\03.live-canvas-demo") as part of a teams meeting. I am able to upload the app. But when I try to add it as a tab, "Save" button is disabled.
![image](https://github.com/microsoft/live-share-sdk/assets/79455376/7146c26d-0002-4fec-8043-a7b8e4d0d527)

I am using Azure app service to deploy and test the app. Am I missing something in the manifest.json file or any other configuration. Please do let me know if anything else is needed.

**Comment by huntj88** [comment]
Can you show what your manifest looks like? After installing an app Teams should show you the config page for the app, but it looks like you're trying to load the main content instead of the config page.

**Comment by Kalyan492** [comment]
> Can you show what your manifest looks like? After installing an app Teams should show you the config page for the app, but it looks like you're trying to load the main content instead of the config page, which handles the saving and notification of success.
> 
> <img alt="image" width="694" src="https://user-images.githubusercontent.com/10103298/249624562-06e94ba9-c7e3-44be-8c57-5d888d9b0af5.png">

Sorry about my earlier bug. I am able to resolve it. I missed to add web.config for Azure app service. Once I have added it, I am able to get the config page and share it to stage. However, if I join the same meeting from a different system, Live share is not working as expected. I could not see both the meetings sharing the Live Canvas state. For your reference, my manifest.json looks like this:

{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
    "version": "1.0.1",
    "manifestVersion": "1.12",
    "id": "a1aff73f-adec-4d10-b016-8280de6ca3e9",
    "packageName": "com.microsoft.teams.liveshareinking",
    "name": {
        "short": "Live Share",
        "full": "Live Share Canvas demo"
    },
    "developer": {
        "name": "Unknown",
        "mpnId": "",
        "websiteUrl": "https://livesharedemo.azurewebsites.net/#/config?inTeams=true",
        "privacyUrl": "https://livesharedemo.azurewebsites.net/#/config?inTeams=true",
        "termsOfUseUrl": "https://livesharedemo.azurewebsites.net/#/config?inTeams=true"
    },
    "description": {
        "short": "Live Share inking demo",
        "full": "Collaborative inking demo powered by Live Share"
    },
    "icons": {
        "outline": "outline.png",
        "color": "color.png"
    },
    "accentColor": "#FFFFFF",
    "configurableTabs": [
        {            
            "configurationUrl": "https://livesharedemo.azurewebsites.net/",
            "canUpdateConfiguration": false,
            "scopes": [
                "groupchat"
            ],
            "context": [
                "meetingSidePanel", 
                "meetingStage"
            ]
        }
    ],
    "validDomains": [
        "livesharedemo.azurewebsites.net"
    ],
    "authorization": {
        "permissions": {
            "orgWide": [],
            "resourceSpecific": [
                {
                    "name": "MeetingStage.Write.Chat",
                    "type": "Delegated"
                },
                {
                    "name": "ChannelMeetingStage.Write.Group",
                    "type": "Delegated"
                },
                {
                    "name": "LiveShareSession.ReadWrite.Chat",
                    "type": "Delegated"
                },
                {
                    "name": "LiveShareSession.ReadWrite.Group",
                    "type": "Delegated"
                }
            ]
        }
    }
}

**Comment by Kalyan492** [comment]
> > Can you show what your manifest looks like? After installing an app Teams should show you the config page for the app, but it looks like you're trying to load the main content instead of the config page, which handles the saving and notification of success.
> > <img alt="image" width="694" src="https://user-images.githubusercontent.com/10103298/249624562-06e94ba9-c7e3-44be-8c57-5d888d9b0af5.png">
> 
> Sorry about my earlier bug. I am able to resolve it. I missed to add web.config for Azure app service. Once I have added it, I am able to get the config page and share it to stage. However, if I join the same meeting from a different system, Live share is not working as expected. I could not see both the meetings sharing the Live Canvas state. For your reference, my manifest.json looks like this:
> 
> { "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.schema.json", "version": "1.0.1", "manifestVersion": "1.12", "id": "a1aff73f-adec-4d10-b016-8280de6ca3e9", "packageName": "com.microsoft.teams.liveshareinking", "name": { "short": "Live Share", "full": "Live Share Canvas demo" }, "developer": { "name": "Unknown", "mpnId": "", "websiteUrl": "https://livesharedemo.azurewebsites.net/#/config?inTeams=true", "privacyUrl": "https://livesharedemo.azurewebsites.net/#/config?inTeams=true", "termsOfUseUrl": "https://livesharedemo.azurewebsites.net/#/config?inTeams=true" }, "description": { "short": "Live Share inking demo", "full": "Collaborative inking demo powered by Live Share" }, "icons": { "outline": "outline.png", "color": "color.png" }, "accentColor": "#FFFFFF", "configurableTabs": [ { "configurationUrl": "https://livesharedemo.azurewebsites.net/", "canUpdateConfiguration": false, "scopes": [ "groupchat" ], "context": [ "meetingSidePanel", "meetingStage" ] } ], "validDomains": [ "livesharedemo.azurewebsites.net" ], "authorization": { "permissions": { "orgWide": [], "resourceSpecific": [ { "name": "MeetingStage.Write.Chat", "type": "Delegated" }, { "name": "ChannelMeetingStage.Write.Group", "type": "Delegated" }, { "name": "LiveShareSession.ReadWrite.Chat", "type": "Delegated" }, { "name": "LiveShareSession.ReadWrite.Group", "type": "Delegated" } ] } } }

Closing this as my issues are resolved. Thanks.
