### ISSUE TITLE
[Feature Request]: Support for Azure Comminication Services

### ISSUE THREAD

**Issue by ryanbliss** [microsoft/live-share-sdk#72]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [X] I have reviewed the FAQ and known issues and did not find my topic

**Describe your user scenario**

Developers building Azure Communication Services applications can use Live Share when joining a Teams meeting through the ACS SDK. 

See their docs: https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-teams-interop?pivots=platform-web

**Describe the solution you'd like**

Integration with ACS

**Comment by ryanbliss** [comment]
This is related to PR #560

**Comment by Kalyan492** [comment]
@ryanbliss , is there any proposed timeline for ACS support?

**Comment by ryanbliss** [comment]
@kalyan492 it is pretty much done, we are just working with private preview partners to solidify requirements. have you signed up for our private preview? https://aka.ms/liveshareacs

**Comment by ryanbliss** [comment]
This is published in preview.
