### ISSUE TITLE
[Feature Request]: Synchronized variable playback rate

### ISSUE THREAD

**Issue by ryanbliss** [microsoft/live-share-sdk#751]
**Describe your user scenario**

Users watching longer videos during scheduled meetings have requested the ability to change playback speeds so they can finish a video within the meeting duration.

**Describe the solution you'd like**

Right now if you change the playback speed of a video the media synchronizer blocks it. We should fix this and also support synchronizing it across clients.

**Comment by huntj88** [comment]
implemented in #756
