### ISSUE TITLE
[JS Bug]: useLiveShareContext not returning joined or joinedError

### ISSUE THREAD

**Issue by JessieLiroff** [microsoft/live-share-sdk#760]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [X] I have reviewed the FAQ and known issues and did not find my topic

**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**

> We're noticing that for one particular partner, `useLiveShareContext` from the teams SDK is not returning `joined` or `joinedError` so it's leaving the partner in a loading state. 

**To Reproduce**

**Note:** We have been unable to reproduce this on our end, this is only happening with one partner. 

> 1. Call the `useLiveShareContext` hook 
> 2. Notice that it does not return either `joined` or `joinedError`

**Expected behavior**

> `useLiveShareContext` should always return either `joined` or `joinedError`, there should not a state where neither of these are returned. 

**Desktop(s) (please complete the following information):**

- OS: Windows

**Additional context**

>  We are not sure if the partner is running teams in the government cloud. 
> The partner's name is **Washoe County**

**Comment by pradeepananth** [comment]
Could you please share their M365 Tenant Id so we can find their cloud type? 
Either they could help provide by looking up in Entra admin center per this document https://learn.microsoft.com/en-us/sharepoint/find-your-office-365-tenant-id
or if we know their domain (after '@' part of their email), we can look it up in this service
https://www.whatismytenantid.com/

**Comment by JessieLiroff** [comment]
@pradeepananth it's `a2a21b60-5625-43fe-a55a-52f5e111d71c`

**Comment by JessieLiroff** [comment]
@pradeepananth we screenshared with them today and got some additional information
1. when using the teams classic app `useLiveShareContext` did not return `joined` or `joinError`
2. when she tried using the website she hit a joinError of `LiveShareProvider: An unknown error occurred while joining container.`
3. The partner is running teams in the goverment cloud

**Comment by pradeepananth** [comment]
@JessieLiroff Thanks for your response. We confirmed that the tenant is indeed Government cloud. Live Share is not supported in this tenant at this time. The expected behavior for Government clouds is that joinedError is returned from the Teams client, and we're investigating why it's not the case.

**Comment by ryanbliss** [comment]
@JessieLiroff also note that we do plan to support Live Share in GCC soon. Azure Fluid Relay is a relatively new Azure service, and the final certification it needs for GCC just got approved very recently. We are taking steps to enable Live Share in GCC but will have to get back to you on timeline.

**Comment by JessieLiroff** [comment]
Thank you! @ryanbliss @pradeepananth A coupleo f additional questions 
1. Is there somewhere in the documentation I can find a list of what isn't supported in GCC? 
2. Is there a list of potential joinErrors? 
3. Is there a reason the error you're sending for GCC not supporting liveShare is so generic?

**Comment by pradeepananth** [comment]
@JessieLiroff Please find responses in quotes:

1. Is there somewhere in the documentation I can find a list of what isn't supported in GCC? 

> Please refer to the Live Share FAQ pag [Live Share FAQ - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-faq)  for list of environments where Live Share is not supported yet. These will be updated when it is available.

2. Is there a list of potential joinErrors?  

> Teams client does send out error with internal error codes, which Live Share core SDK will send as is. However, it looks like `Live-share-react` package is abstracting this away and we will need to fix this.
FYI @ryanbliss 

3. Is there a reason the error you're sending for GCC not supporting liveShare is so generic? 

> We had relied on `teams-js` getContext API to identify the environment based on this field: `teamsContext.app.host.ringId`, but since this is breaking in new Teams, we are not handling this in the Live Share SDK, and we have filed a bug on our internal team that owns this SDK. We will keep you posted once this is fixed. 
In the old Teams client, the app can check against this field and indicate to the user this environment is not supported. That field would have value as `general_gcc` if Government Cloud.

**Comment by JessieLiroff** [comment]
@ryanbliss any update on when you plan to support Live Share in GCC?

**Comment by pradeepananth** [comment]
@JessieLiroff  We have fixed an issue for Live Share in GCC and should be working now. Please validate the same on your side.

**Comment by ryanbliss** [comment]
@JessieLiroff Live Share should be supported in Live Share in GCC, please let me know if there are any other issues on your end. Closing for now :)
