### ISSUE TITLE
[Feature Request]: Update version prompts or call to action

### ISSUE THREAD

**Issue by huntj88** [microsoft/live-share-sdk#761]
**Describe your user scenario**
Users should be aware when new versions of live share are available

**Describe the solution you'd like**

- if using local live share host for dev environment, console log version update details
- npm install update mesage
- npx script to update all packages related to live share

**Comment by ryanbliss** [comment]
This can be addressed via [deprecating packages in NPM](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions). Closing this for now, can re-open in the future if the need arises.
