### ISSUE TITLE
[Bug]: android

### ISSUE THREAD

**Issue by Becar21** [microsoft/live-share-sdk#764]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [ ] I have reviewed the FAQ and known issues and did not find my topic

**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**

> Provide a clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:

**Expected behavior**

> Provide a clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop(s) (please complete the following information):**

- OS: [e.g. macOS]

**Smartphone (please complete the following information):**

**Additional context**

> Add any other context about the problem here.

**Comment by ryanbliss** [comment]
Hello! Can you please share more information about this bug?
