### ISSUE TITLE
[Bug]: Sharing content to screen will error for unverified users if they are marked as presenter

### ISSUE THREAD

**Issue by RichieMcCaff** [microsoft/live-share-sdk#798]
### Please review [FAQ and Known issues](https://github.com/microsoft/live-share-sdk/issues/8) before filing a new item!

- [x] I have reviewed the FAQ and known issues and did not find my topic

**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**
In a pre-orgranised meeting that includes external/unverified users.
If an app using liveshare presents content to the main stage and any of these unverified users are marked as presenters (The default role applied) they will see the following error:

<img width="460" alt="Screenshot 2024-09-24 at 18 28 21" src="https://github.com/user-attachments/assets/64e7eb44-ada3-41b1-8a73-e7f3c9045c78">

Switching these users to attendee roles will allow content to present to their screens.

**To Reproduce**

> Steps to reproduce the behavior:

1. Create a new meeting in teams
2. Invite external users to the meeting
3. Mark the external users as presenter roles
4. Use an liveshare app to present content to the screen
5. Error appears on External users screen

**Screenshots**
User marked as presenter error:
<img width="1915" alt="Screenshot 2024-09-24 at 18 40 22" src="https://github.com/user-attachments/assets/afe51e6d-c4f8-4fc4-a637-33d276219f13">

User marked as Attendee it works:
<img width="1914" alt="Screenshot 2024-09-24 at 18 40 43" src="https://github.com/user-attachments/assets/7a5b2370-4388-4003-9ff7-d1f3ecb35a44">

**Desktop(s) (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version 128.0.6613.120

**Additional context**
> Seeing the same behaviour on the teams app as well

**Comment by ryanbliss** [comment]
Just seeing this now, I'll get some engineers to investigate this ASAP. Thanks for the detailed ticket.

**Comment by RichieMcCaff** [comment]
> Just seeing this now, I'll get some engineers to investigate this ASAP. Thanks for the detailed ticket.

@ryanbliss I actually raised this in the teams-js [repo](https://github.com/OfficeDev/microsoft-teams-library-js/issues/2549) since I believe I raised this one here in error seeing as the error occurs from a teams-js module.

We can probably just close this.

**Comment by ryanbliss** [comment]
Great thank you @RichieMcCaff!
